name: Node.js CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

  
    - name: Install dependencies
      run: npm install

    - name: Run sever
      run: npm run start


   
   
